version: '3.8'

services:
  test_app:
    build: form_api/.
    container_name: test_app
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:${MONGO_VERSION}
    restart: unless-stopped
    container_name: mongo_test
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  tests:
    container_name: tests
    build:
      context: form_api/tests/functional/.
    env_file:
      - .env
    depends_on:
      - test_app
    entrypoint: >
      sh -c "pip install -r /tests/functional/requirements.txt
      && python3 /tests/functional/utils/wait_for_api.py
      && pytest /tests/functional/src"
